import type { Theme } from "../types";

export const themes: Theme[] = [
  {
    name: "mission-control",
    category: "dark",
    tokens: {
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#161b22",
      "--bg-tertiary": "#0a0e14",
      "--accent": "#58a6ff",
      "--accent-dim": "#1f6feb",
      "--text-primary": "#e6edf3",
      "--text-secondary": "#8b949e",
      "--status-ok": "#3fb950",
      "--status-warn": "#d29922",
      "--status-err": "#f85149",
      "--border": "#30363d",
    },
  },
  {
    name: "daylight",
    category: "light",
    tokens: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f6f8fa",
      "--bg-tertiary": "#eaeef2",
      "--accent": "#0969da",
      "--accent-dim": "#54aeff",
      "--text-primary": "#1f2328",
      "--text-secondary": "#656d76",
      "--status-ok": "#1a7f37",
      "--status-warn": "#9a6700",
      "--status-err": "#cf222e",
      "--border": "#d0d7de",
    },
  },
  {
    name: "obsidian-light",
    category: "light",
    tokens: {
      "--bg-primary": "#fafafa",
      "--bg-secondary": "#f0f0f0",
      "--bg-tertiary": "#e5e5e5",
      "--accent": "#6366f1",
      "--accent-dim": "#818cf8",
      "--text-primary": "#18181b",
      "--text-secondary": "#71717a",
      "--status-ok": "#22c55e",
      "--status-warn": "#eab308",
      "--status-err": "#ef4444",
      "--border": "#d4d4d8",
    },
  },
  {
    name: "obsidian",
    category: "dark",
    tokens: {
      "--bg-primary": "#1e1e2e",
      "--bg-secondary": "#28283d",
      "--bg-tertiary": "#16162a",
      "--accent": "#818cf8",
      "--accent-dim": "#6366f1",
      "--text-primary": "#e2e8f0",
      "--text-secondary": "#94a3b8",
      "--status-ok": "#4ade80",
      "--status-warn": "#facc15",
      "--status-err": "#f87171",
      "--border": "#334155",
    },
  },
  {
    name: "nord",
    category: "dark",
    tokens: {
      "--bg-primary": "#2e3440",
      "--bg-secondary": "#3b4252",
      "--bg-tertiary": "#242933",
      "--accent": "#88c0d0",
      "--accent-dim": "#5e81ac",
      "--text-primary": "#eceff4",
      "--text-secondary": "#d8dee9",
      "--status-ok": "#a3be8c",
      "--status-warn": "#ebcb8b",
      "--status-err": "#bf616a",
      "--border": "#4c566a",
    },
  },
  {
    name: "dracula",
    category: "dark",
    tokens: {
      "--bg-primary": "#282a36",
      "--bg-secondary": "#343746",
      "--bg-tertiary": "#1e1f29",
      "--accent": "#bd93f9",
      "--accent-dim": "#6272a4",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#6272a4",
      "--status-ok": "#50fa7b",
      "--status-warn": "#f1fa8c",
      "--status-err": "#ff5555",
      "--border": "#44475a",
    },
  },
  {
    name: "monokai",
    category: "dark",
    tokens: {
      "--bg-primary": "#272822",
      "--bg-secondary": "#3e3d32",
      "--bg-tertiary": "#1e1f1c",
      "--accent": "#66d9ef",
      "--accent-dim": "#a6e22e",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#75715e",
      "--status-ok": "#a6e22e",
      "--status-warn": "#e6db74",
      "--status-err": "#f92672",
      "--border": "#49483e",
    },
  },
  {
    name: "github-dark",
    category: "dark",
    tokens: {
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#161b22",
      "--bg-tertiary": "#010409",
      "--accent": "#58a6ff",
      "--accent-dim": "#1f6feb",
      "--text-primary": "#c9d1d9",
      "--text-secondary": "#8b949e",
      "--status-ok": "#3fb950",
      "--status-warn": "#d29922",
      "--status-err": "#f85149",
      "--border": "#30363d",
    },
  },
  {
    name: "solarized-dark",
    category: "dark",
    tokens: {
      "--bg-primary": "#002b36",
      "--bg-secondary": "#073642",
      "--bg-tertiary": "#001e26",
      "--accent": "#268bd2",
      "--accent-dim": "#2aa198",
      "--text-primary": "#fdf6e3",
      "--text-secondary": "#839496",
      "--status-ok": "#859900",
      "--status-warn": "#b58900",
      "--status-err": "#dc322f",
      "--border": "#586e75",
    },
  },
  {
    name: "centcom",
    category: "dark",
    tokens: {
      "--bg-primary": "#1a1a0d",
      "--bg-secondary": "#252510",
      "--bg-tertiary": "#0f0f08",
      "--accent": "#EF9F27",
      "--accent-dim": "#BA7517",
      "--text-primary": "#EF9F27",
      "--text-secondary": "#B4A882",
      "--status-ok": "#8fbd3a",
      "--status-warn": "#EF9F27",
      "--status-err": "#E24B4A",
      "--border": "#3a3a00",
    },
  },
  {
    name: "high-contrast",
    category: "accessibility",
    tokens: {
      "--bg-primary": "#000000",
      "--bg-secondary": "#0a0a0a",
      "--bg-tertiary": "#000000",
      "--accent": "#00ffff",
      "--accent-dim": "#0088ff",
      "--text-primary": "#ffffff",
      "--text-secondary": "#cccccc",
      "--status-ok": "#00ff00",
      "--status-warn": "#ffff00",
      "--status-err": "#ff0000",
      "--border": "#ffffff",
    },
  },
  {
    name: "high-contrast-light",
    category: "accessibility",
    tokens: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f5f5f5",
      "--bg-tertiary": "#eeeeee",
      "--accent": "#0000cc",
      "--accent-dim": "#0055aa",
      "--text-primary": "#000000",
      "--text-secondary": "#333333",
      "--status-ok": "#006600",
      "--status-warn": "#886600",
      "--status-err": "#cc0000",
      "--border": "#000000",
    },
  },
  {
    name: "system",
    category: "auto",
    tokens: {
      // Auto theme defaults to mission-control; actual switching handled in useTheme
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#161b22",
      "--bg-tertiary": "#0a0e14",
      "--accent": "#58a6ff",
      "--accent-dim": "#1f6feb",
      "--text-primary": "#e6edf3",
      "--text-secondary": "#8b949e",
      "--status-ok": "#3fb950",
      "--status-warn": "#d29922",
      "--status-err": "#f85149",
      "--border": "#30363d",
    },
  },
];
